# application.yml

server:
    port: 9998
    
ledstrip:
    rows: 3
    columns: 3
    python_program_test: src\main\python\ledstrip_test.py
    python_program_prod: src\main\python\ledstrip.py