# application.yml

server:
    port: 9999
management:
    port: 8999
endpoints:
    sensitive: false
    enabled: true
    health:
        sensitive: false
management.security.enabled: false 
    
ledstrip:
    rows: 3
    columns: 3
    python_update: src\main\python\ledstrip_test.py
    python_check: src\main\python\ledstrip_num_test.py

spring:
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: ledstrip
    
---
spring:
    profiles: test
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: ledstrip_test

---
spring:
    profiles: raspberry
ledstrip:
    python_update: src\main\python\ledstrip.py
    python_check: src\main\python\ledstrip_num.py
    